site_name: Atomist Documentation
site_description: Atomist Documentation
site_author: The Atomist Team
repo_name: GitHub
repo_url: https://github.com/atomist/docs
edit_uri: edit/master/docs/
copyright: "&copy; 2019 Atomist, Inc."
extra:
  main_site_url: https://atomist.com/
  social:
    - type: medium
      link: https://blog.atomist.com/
    - type: github
      link: https://github.com/atomist
    - type: twitter
      link: https://twitter.com/atomist
    - type: slack
      link: https://join.atomist.com/
theme:
  name: material
  favicon: "img/favicon.ico"
  logo: img/atomist-developer-docs-logo.png
  palette:
    primary: white
    accent: teal
  custom_dir: "theme"
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/intercom.js
markdown_extensions:
  - markdown_include.include:
      base_path: "common"
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - smarty
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
nav:
  - Welcome: index.md
  - Getting Started: getting-started.md
  - Developer Quick Start: quick-start.md
  - Using Atomist:
      - Introduction: user/index.md
      - Atomist web interface: user/dashboard.md
      - Source Control: user/github.md
      - Slack: user/slack.md
      - Built-in Chat Integrations: user/lifecycle.md
      - Supported Integrations: user/integrations.md
  - Developer Guide:
      - Overview: developer/index.md
      - SDM Development:
        - About the SDM: developer/sdm.md
        - Architecture: developer/architecture.md
        - Prerequisites: developer/prerequisites.md
        - Team Mode: developer/team.md
        - Local Mode: developer/local.md
        - Deploying your SDM: developer/sdm-deploy.md
        - Debugging an SDM: developer/sdm-debug.md
        - Goals:
            - Create Goals: developer/goal.md
            - Setting Goals: developer/set-goals.md
            - Doing More with Goals: developer/goals-more.md
        - Event Listeners: developer/event.md
        - Builds:
          - Build Goal: developer/build.md
          - Integrations: user/ci.md
          - Generic Builder: developer/spawn-builder.md
        - Deploys: developer/deploy.md
        - Code Inspections: developer/inspect.md
        - Code Transforms:
            - Transforms: developer/transform.md
            - Autofixes: developer/autofix.md
            - Project: developer/project.md
            - Path Expressions: developer/pxe.md
        - Commands: developer/commands.md
        - Project Generators: developer/create.md
        - Security Model: developer/security.md
        - TypeScript Hints: developer/typescript.md
        - Troubleshooting: developer/troubleshoot.md
        - More Details:
          - Fingerprints: developer/fingerprint.md
          - SDM Configuration: developer/config.md
          - Running External Commands: developer/spawn.md
          - Logging: developer/logging.md
          - Push Tests: developer/push-test.md
          - RepoRef: developer/reporef.md
          - HTTP Calls in an SDM: developer/http.md
          - Custom GraphQL Queries: developer/graphql.md
          - Chat Messages: developer/slack.md
          - Command Line Interface: developer/cli.md
          - SDM Concepts: developer/sdm-concepts.md
      - API Reference:
        - automation-client: https://atomist.github.io/automation-client/
        - sdm: https://atomist.github.io/sdm/
        - sdm-pack-build: https://atomist.github.io/sdm-pack-build/
        - sdm-pack-checkstyle: https://atomist.github.io/sdm-pack-checkstyle/
        - sdm-pack-cloudfoundry: https://atomist.github.io/sdm-pack-cloudfoundry/
        - sdm-pack-k8s: https://atomist.github.io/sdm-pack-k8s/
        - sdm-pack-sloc: https://atomist.github.io/sdm-pack-sloc/
        - sdm-pack-spring: https://atomist.github.io/sdm-pack-spring/
        - sdm-pack-sonarqube: https://atomist.github.io/sdm-pack-sonarqube/
      - Glossary: developer/glossary.md
  - Extensions:
    - Extension Packs: pack/index.md
    - Build: pack/build.md
    - Changelog: pack/changelog.md
    - Checkstyle: pack/checkstyle.md
    - Cloud Foundry: pack/pcf.md
    - Docker: pack/docker.md
    - Kubernetes: pack/kubernetes.md
    - Issue: pack/issue.md
    - Lines of Code: pack/sloc.md
    - Markdown: pack/markdown.md
    - Node: pack/node.md
    - Sonarqube: pack/sonarqube.md
    - Spring: pack/spring.md
  - Support: support.md
